### PR TITLE
Reuse serviceInstance for retries Fixes gh-840

### PR DESCRIPTION
**Pull request by apikozh**

### CODE REVIEW

**Review by spencergibb — CHANGES_REQUESTED** [review]
please add a test

**Comment by oliverlockwood** [comment]
It's not the unit test that @spencergibb is presumably asking for, but FWIW as noted in https://github.com/spring-cloud/spring-cloud-openfeign/issues/840#issuecomment-1450857765 I've manually tested this change with the reproducing application I built, and it appears to fix the issue.

**Comment by apikozh** [comment]
Added tests

**Comment by OlgaMaciaszek** [comment]
Fixes gh-840.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
@apikozh, thanks a lot for working on this. Just a few cosmetic things:
- please add your full name and surname with `@author` tag in the javadocs of both modified classes
- please update the copyright line on top of both files from "2022" to "2023".
Also, please submit this PR against `3.1.x` instead of `main`, so that we can include it in the `2021.x` release train as well.

**Comment by apikozh** [comment]
@OlgaMaciaszek Done

**Review by OlgaMaciaszek — APPROVED** [review]
Thanks, @apikozh. LGTM.

**Comment by oliverlockwood** [comment]
Great work @apikozh!

@OlgaMaciaszek  in due course, please would you advise which releases this fix makes it into?
Many thanks.

**Comment by OlgaMaciaszek** [comment]
Sure, it will make it to `3.1.7` and `4.0.2`.

**Pull request merged**
