### PR TITLE
Use property 'number' in JSON Page representation instead of 'page'

### PR DESCRIPTION
**Pull request by rvervaek**
Fixes gh-237

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rvervaek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=319)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=319) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rvervaek Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=319)!

**Comment by ryanjbaxter** [comment]
Can you submit this against the 2.2.x branch?

**Comment by rvervaek** [comment]
Will do

**Pull request closed without merging**
