### PR TITLE
change "Sprig Cloud" to  "Spring Cloud"

### PR DESCRIPTION
**Pull request by LiuzeyangGitHub**
Spelling mistakes

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@LiuzeyangGitHub Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=367)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=367) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@LiuzeyangGitHub Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=367)!

**Comment by LiuzeyangGitHub** [comment]
I dot know why tests failed,I'm not change other code ,just doc.

**Comment by LiuzeyangGitHub** [comment]
@pivotal-issuemaster  I dot know why tests failed,I'm not change other code ,just doc.

**Comment by OlgaMaciaszek** [comment]
@LiuzeyangGitHub thanks for spotting and fixing the typo. Merged within https://github.com/spring-cloud/spring-cloud-openfeign/commit/5fea4f3b35aed2fb0f651165b6ea84a5b332a553.

**Pull request closed without merging**
