### PR TITLE
Sort Support for feign pagination

### PR DESCRIPTION
**Pull request by cbezmen**
PageJacksonModule doesn't support for sort operations.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Also be sure to add some documentation that this would now be supported

**Comment by cbezmen** [comment]
Hi Ryan, 
I am new to this. Could you help me about documentation. Where should I write the documentation. etc.
@ryanjbaxter

**Comment by cbezmen** [comment]
I created new PR for new branch 2.2.x.
https://github.com/spring-cloud/spring-cloud-openfeign/pull/329

**Comment by OlgaMaciaszek** [comment]
@cbezmen The documentation should be added to `spring-cloud-openfeign.adoc`.

Closing this PR in favour of https://github.com/spring-cloud/spring-cloud-openfeign/pull/329

**Pull request closed without merging**
