### PR TITLE
polishing FeignClientsRegistrar

### PR DESCRIPTION
**Pull request by birariro**
```getName (Map<String, Object>)``` does not need to be for test purposes.

### CODE REVIEW

**Review by OlgaMaciaszek — COMMENTED** [review]
Hello @birariro, I'm not sure why you've proposed this change. We do need to use `beanFactory` to properly resolve the attributes.

**Comment by birariro** [comment]
Hello @OlgaMaciaszek 

```String getName(ConfigurableBeanFactory beanFactory, Map<String, Object> attributes)```
Because the only way to call is ```String getName(Map<String, Object> attributes)```
Isn't beanFactory always null?

And 
```/* for testing */ String getName(Map<String, Object> attributes) ``` 
If you look at the comments, it says it's for testing, but if it's unnecessary, it looked better without it

**Comment by spencergibb** [comment]
Keep the for testing comment

**Comment by OlgaMaciaszek** [comment]
@birariro  It's helpful to know that the visibility level has been raised for testing purposes. That's why we put these comments there. I thought `getName` was also called at a different point, but possibly after some refactoring it isn't, so right, we can change that.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks @birariro. Looks good. Can you please just add your full name and surname with `@author` tag to the javadoc of the class and update the date in the license comment to `2013-2024`?

**Comment by birariro** [comment]
@OlgaMaciaszek I have applied the changes as requested.

**Pull request merged**
