### PR TITLE
Support regex expression for @PathVariable

### PR DESCRIPTION
**Pull request by quaff**
Fix gh-576

### CODE REVIEW

**Comment by quaff** [comment]
Please review @OlgaMaciaszek

**Comment by OlgaMaciaszek** [comment]
Fixes gh-576.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
@quaff Thanks for submitting the PR.  In general, the change looks good. However, please add information about the feature [to the docs](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/docs/src/main/asciidoc/spring-cloud-openfeign.adoc).

**Comment by quaff** [comment]
@OlgaMaciaszek It is bug fix, such feature in Spring MVC existed before Spring Cloud created, people should expect it works without checking the docs, WDYT?

**Comment by OlgaMaciaszek** [comment]
@quaff  Feign Client is not the same as Spring MVC. We strive to provide integration for as many features as possible within SC OpenFeign, but it's a separate lib. It's never a good idea to add info to docs (just one sentence with a simple example will be fine).

**Review by OlgaMaciaszek — APPROVED** [review]
LGTM

**Pull request merged**
