### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by wzslw**
多次引用

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wzslw Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=88)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=88) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wzslw Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=88)!

**Comment by ryanjbaxter** [comment]
Could you explain in English what the purpose is?

**Comment by wzslw** [comment]
This dependency is declared multiple times

> Could you explain in English what the purpose is?

**Pull request merged**
