### PR TITLE
Issue 490

### PR DESCRIPTION
**Pull request by cbezmen**
* Changed: feign.client, feign.compression, feign.httpclient, feign.okhttp, feign.encoder, feign.autoconfiguration.jackson.enabled, feign.circuitbreaker
* Updated: All Documents are updated
* Updated: All tests are updated

### CODE REVIEW

**Comment by cbezmen** [comment]
Fixes gh-490

**Comment by spencergibb** [comment]
This is a breaking change and not scheduled until next year

**Comment by OlgaMaciaszek** [comment]
@cbezmen Thanks for getting this done. This will, however, need to wait till our next major release train (codename `Kilburn`). Will ice-box it till then.

**Comment by OlgaMaciaszek** [comment]
Hello, @cbezmen would you like to submit a similar PR against the current `main` branch?

**Comment by cbezmen** [comment]
I will work on it. @OlgaMaciaszek

**Pull request closed without merging**
