### PR TITLE
Delete '/' at the end of url

### PR DESCRIPTION
**Pull request by birariro**
#707

Since the PR is not going on anymore
I added a test.

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hello @birariro. Please see the related issue: https://github.com/spring-cloud/spring-cloud-openfeign/issues/1070. This needs to be configurable. Let me know if you'd like to work on it. If not, I'll pick it up.

**Comment by OlgaMaciaszek** [comment]
Fixes gh-1070.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks @birariro. Please see the related issue: https://github.com/spring-cloud/spring-cloud-openfeign/issues/1070. This needs to be configurable. Also, since you've picked changes over from gh-707, could you please cherry-pick them, so that the original commit is included.

**Comment by birariro** [comment]
@OlgaMaciaszek Done cherry-pick #707

**Comment by birariro** [comment]
@OlgaMaciaszek 

I checked the issue of #1070
For spring-projects/spring-framework, I think they want to use the correct URL
If so, shouldn't I use the correct URL when using SC OpenFeign?

**Comment by OlgaMaciaszek** [comment]
Hello @birariro, as noted [here](https://github.com/spring-cloud/spring-cloud-openfeign/issues/1070#issuecomment-2374635377), this change needs to be configurable, by default disabled, in order to avoid breaking compatibility.

**Comment by birariro** [comment]
Hello @OlgaMaciaszek 

I've looked at the issue you've given me, but I think I'll have difficulty solving it with my ability.
Can you pick up the work?

**Comment by OlgaMaciaszek** [comment]
Sure, will do.

**Pull request closed without merging**
