### PR TITLE
Up Feign version and using DTO in GET request as QueryMap

### PR DESCRIPTION
**Pull request by MikeSafonov**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@MikeSafonov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=34)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=34) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@MikeSafonov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=34)!

**Comment by ryanjbaxter** [comment]
Can you provide a better description of what this is fixing/enhancing?

**Comment by MikeSafonov** [comment]
Since version 9.7 OpenFeign supports using POJO as QueryMap in GET requests [#667](https://github.com/OpenFeign/feign/pull/667)
I added ability to use this functionality via RequestParam annotation (see RequestParamParameterProcessor).

**Comment by ryanjbaxter** [comment]
Can you please resolve the conflicts?

**Comment by ryanjbaxter** [comment]
Or maybe now that I am looking at this maybe you just need to switch your PR to target the 2.0.x branch.

**Comment by ryanjbaxter** [comment]
Closing due to lack of requested feedback.

**Pull request closed without merging**
