### PR TITLE
Update appendix link in spring-cloud-openfeign doc

### PR DESCRIPTION
**Pull request by terceser**
Current appendix link redirect to a 404 page

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hello, @terceser . Thanks for submitting the PR. Could you please link to where you are getting a `404`? I was not able to reproduce this issue.

**Comment by terceser** [comment]
Hello @OlgaMaciaszek, here is the link on the main branch https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/docs/src/main/asciidoc/spring-cloud-openfeign.adoc
(screenshot bellow)
image

[the Appendix page](https://github.com/spring-cloud/spring-cloud-openfeign/blob/main/docs/src/main/asciidoc/appendix.html) redirect to a 404 page 
(screenshot bellow)
image

**Comment by OlgaMaciaszek** [comment]
Ah, I see. That is because it's accessed from the README in GH. The actual reference site is [here](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/). When you access it from there, you'll get [HTML](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/appendix.html).

**Comment by terceser** [comment]
ah I see ^^ please disregard my PR

**Pull request closed without merging**
