### PR TITLE
refactor: replace `@RequestMapping` annotations

### PR DESCRIPTION
**Pull request by jkschneider**
Just trying to help use the more targeted annotations like `@GetMapping` or `@PostMapping` instead. Hope it helps :)

Co-authored-by: Moderne <team@moderne.io>

### CODE REVIEW

**Review by spencergibb — APPROVED** [review]

**Comment by jkschneider** [comment]
@spencergibb I'll look at why `@RequestMapping` import didn't get removed as it should have. Sorry for the noise.

**Comment by jkschneider** [comment]
Should be good to go now :)

**Review by spencergibb — APPROVED** [review]

**Comment by OlgaMaciaszek** [comment]
Thanks, @jkschneider Looks great - have been doing it manually from time to time, but did not have time to do a lot of them. Will have to switch selected ones back to `@RequestMapping`, though, cause we also need to verify that there's no problem with handling them with FeignClient.

**Comment by OlgaMaciaszek** [comment]
Merged within 769b38c5c16ad0ab7eec057adbc2979c62fae3ab.

**Pull request closed without merging**
