### PR TITLE
Add a CookieValueParameterProcessor to support @CookieValue

### PR DESCRIPTION
**Pull request by topikachu**
Simplify Feign client which needs multiple cookies in the request.

### CODE REVIEW

**Comment by MarkDcc** [comment]
This function is very useful. we hope we can use it in the latest version.

**Comment by MarkDcc** [comment]
@OlgaMaciaszek Can you help to check with this?

**Comment by topikachu** [comment]
> This function is very useful. we hope we can use it in the latest version.

Please tell me if need any more change.

**Comment by OlgaMaciaszek** [comment]
@topikachu, thanks for the PR. @topikachu @MarkDcc will review this week.

**Comment by spencergibb** [comment]
Why introduce a custom annotation when Spring MVC already has one https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/CookieValue.html

**Comment by topikachu** [comment]
> Why introduce a custom annotation when Spring MVC already has one https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/CookieValue.html

Well, thanks for your information. Change code to use @CookieValue from Spring MVC

**Comment by topikachu** [comment]
@MarkDcc and @spencergibb,
I use the spring mvc @CookieValue instead of the custom one. Please check the new code.
Thanks.

**Review by OlgaMaciaszek — APPROVED** [review]
LGTM

**Pull request merged**
