### PR TITLE
Added support for MultipartFile

### PR DESCRIPTION
**Pull request by Hronom**
Proposed solution for https://github.com/spring-cloud/spring-cloud-openfeign/issues/62

### Notes
The solution is based on
```
        <dependency>
            <groupId>io.github.openfeign.form</groupId>
            <artifactId>feign-form-spring</artifactId>
            <version>3.3.0</version>
        </dependency>
```

Class `feign.form.spring.SpringFormEncoder` was added inside `org.springframework.cloud.openfeign.support.SpringEncoder` because it's doesn't has some checks:
1. Check of  `bodyType` on null.
`org.springframework.cloud.openfeign.support.SpringEncoder#encode` don't handle situation when `bodyType` is null.

2. No check for content type `multipart/form-data` in header. 
`feign.form.FormEncoder` requires `multipart/form-data` in header for proper processing.

All this checks added and tests are passed.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Hronom Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=65)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=65) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Hronom Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=65)!

**Comment by ryanjbaxter** [comment]
Can you submit this PR against the 2.0.x branch?

**Comment by Hronom** [comment]
@ryanjbaxter changed

**Comment by Hronom** [comment]
@ryanjbaxter Oh I think I need to apply changes on that branch since it will push some changes from master...

**Comment by Hronom** [comment]
Closed.
New here https://github.com/spring-cloud/spring-cloud-openfeign/pull/66

**Pull request closed without merging**
