### PR TITLE
Add builder for feign clients - master

### PR DESCRIPTION
**Pull request by sdoeringNew**
Utilizes the logic from the registrar and the factory bean. The changes to them have been made minimal invasive.

Fixes gh-42

### CODE REVIEW

**Comment by sdoeringNew** [comment]
The ``FeignClientsRegistrar`` needs to be refactored. All the helping stuff can be splitted into a separate class. That would allow better reusage in the ``FeignClientBuilder``. And it would decrease general complexity.

I haven't changed it in this PR to ease the review.

**Comment by ryanjbaxter** [comment]
I think you might want to target the 2.0.x (for Finchley) branch instead of master

**Comment by sdoeringNew** [comment]
I've created a second pull request for the 2.0.x branch.
However a builder for the master branch would be neat, too.

**Comment by ryanjbaxter** [comment]
We just need one PR for 2.0.x and we will merge it forward into master

**Comment by ryanjbaxter** [comment]
Yup sorry.

**Comment by sdoeringNew** [comment]
;-)

**Pull request closed without merging**
