### PR TITLE
Migrate from Spring Security OAuth to OAuth2 support in Spring Security

### PR DESCRIPTION
**Pull request by dangzhicairang**
#644 Migrate from Spring Security OAuth to OAuth2 support in Spring Security
Open the feature by "spring.cloud.openfeign.oauth2.enabled=true' and the OAuth2AccessTokenInterceptor will inject OAuth2 Token in request header.
By default acquire token by all configured client, if specific the property "spring.cloud.openfeign.oauth2.specifiedClientIds", then it will be used.

### CODE REVIEW

**Review by OlgaMaciaszek — COMMENTED** [review]
Hello @dangzhicairang, thanks for submitting this PR. It has been very helpful.
Setting headers in the Feign `RequestTemplate` looks good. However, I am not exactly convinced by the `findAny` logic regarding the OAuth2 client ids, where the first working `ClientRegistration` from a list of either specified ids or properties is used. I think for security purposes it makes more sense where the user knows exactly which OAuth2 client id they want to use. However, since we can have multiple Feign clients in the application, I'm thinking it might also make sense to retrieve OAuth2 clientIds from Feign Client load-balancing service ids.

**Comment by dangzhicairang** [comment]
> Hello @dangzhicairang, thanks for submitting this PR. It has been very helpful. Setting headers in the Feign `RequestTemplate` looks good. However, I am not exactly convinced by the `findAny` logic regarding the OAuth2 client ids, where the first working `ClientRegistration` from a list of either specified ids or properties is used. I think for security purposes it makes more sense where the user knows exactly which OAuth2 client id they want to use. However, since we can have multiple Feign clients in the application, I'm thinking it might also make sense to retrieve OAuth2 clientIds from Feign Client load-balancing service ids.
> 
> Normally, I would just add this to the PR review. However, since I'd like to get this migration done soon, I have created [a new branch](https://github.com/spring-cloud/spring-cloud-openfeign/commits/migrate-oauth-support-new) based on top of yours (retaining your commits) with those changes. I have also removed the legacy OAuth components and fixed the properties (since the OAuth2 client lib is part of Spring, we do not need to add the dependency to SC OF dependency pom and we should not explicitly specify the version, it will come from the Spring bom).

@OlgaMaciaszek Thanks for your reply, i saw the new branch and understood the logic you said. Which i use the `findAny clientId` logic is for migrate from application that already register some clients, however there are real problems with security, now it looks work well, thanks again.

**Comment by OlgaMaciaszek** [comment]
Sure, thanks for the contribution :)

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-openfeign/commits/migrate-oauth-support-new.

**Pull request closed without merging**
