### PR TITLE
Add test support for @RequestMapping(path = "/"). Fixes gh-387.

### PR DESCRIPTION
**Pull request by calaroche**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@calaroche Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=409)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=409) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@calaroche Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=409)!

**Comment by OlgaMaciaszek** [comment]
Thanks, @calaroche. Will review this tomorrow.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks @calaroche In general,  these tests are good and can be added anyway, they do not verify that issue. When you check out a commit before the fix (for example, d3da7e16e822c451e4a2beb0d3b3116132d262ad), add these tests there and run them against that commit, they still pass. For this task, we will need to add a test that will fail against that commit and, therefore, reproduce the issue.

**Comment by OlgaMaciaszek** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
