### PR TITLE
New Feature 

### PR DESCRIPTION
**Pull request by harishwar-babu**
Added new Feature JWT-Access-Token-Interceptor
* In the previous versions. developers need to manually implement the requestInterceptor. to pass the token between services.
* By including this feature. Developer just need to create a bean, for this class and there by the implementation is done by default.

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hello, @harishwar-babu, a separate `HttpServletRequest` object is created for every HTTP request. How would you inject it as a field during bean creation?

**Comment by harishwar-babu** [comment]
As HttpServletRequest is already a component. So whenever the developer
tries to use my Feature called JwtAccessTokenInterceptor, they need to
create a bean for my feature upon creation, this httpservletRequest is also
being created and injected by using the field injection strategy.

Thanks
Harish Babu

**Comment by OlgaMaciaszek** [comment]
Thanks, @harishwar-babu, but we are not going to be adding this feature at this point.

**Comment by harishwar-babu** [comment]
May I know the reason?

Thanks

**Comment by OlgaMaciaszek** [comment]
`HttpServletRequest` objects correspond to specific requests, while beans should correspond to components present throughout the lifecycle of the application.

**Pull request closed without merging**
