### PR TITLE
adds support for response interceptor configuration. Fixes gh-802

### PR DESCRIPTION
**Pull request by doumdoum**

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Fixes gh-802.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hello, @doumdoum. Thanks for submitting the PR. LGTM. However, please add your full name with `@author` tag to the javadocs of the classes that you've edited.

**Comment by OlgaMaciaszek** [comment]
> Hello, @doumdoum. Thanks for submitting the PR. LGTM. However, please add your full name with `@author` tag to the javadocs of the classes that you've edited.

I want to make sure we get this into the release, so I'll just add it based on your GH profile.

**Comment by doumdoum** [comment]
Sorry @OlgaMaciaszek i didn't get your requests. 
Many thx for accepting that PR.

**Comment by OlgaMaciaszek** [comment]
No problem. Thanks for the contribution @doumdoum.

**Pull request merged**
