### PR TITLE
Switch remaining jUnit4 tests to jUnit jupiter

### PR DESCRIPTION
**Pull request by Syemon**
Fixes [#563]
I am not sure about this test. It passes if I run it directly through maven command, but It fails with ```org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.http.impl.client.CloseableHttpClient' available``` if I run it through inteliJ.
```java
@Test
public void hc4ShouldWinEvenHc5ConfigEnabled() {
	ConfigurableApplicationContext context = new SpringApplicationBuilder()
			.properties("feign.httpclient.hc5.enabled=true").web(WebApplicationType.NONE)
			.sources(HttpClientConfiguration.class, FeignAutoConfiguration.class).run();

	verifyHc4BeansAvailable(context);

	if (context != null) {
		context.close();
	}
}
```

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
@Syemon we treat mvn runs as the source of truth. Might be some issue with IntelliJ. Does this test behave differently with your changes than without them when you run it from IDE (i.e. was it passing in the IDE before your changes or not?)?

**Comment by Syemon** [comment]
@OlgaMaciaszek it Was passing before change.

**Comment by OlgaMaciaszek** [comment]
Ok. Will check that.

**Comment by OlgaMaciaszek** [comment]
@Syemon that test works fine for me, both with Maven and through IDE, so it's probably just a local issue. We can be disregarded. Please resubmit your changes against the `main` branch (merge in any newly added code from `main` to your branch first) - will review the whole PR then.

**Comment by Syemon** [comment]
Thanks, I was not aware. I will make a new branch just for my changes.

**Pull request merged**
