### PR TITLE
Issue #549

### PR DESCRIPTION
**Pull request by cbezmen**
* Fixed: Form URL Encoded bug fixed.

### CODE REVIEW

**Comment by cbezmen** [comment]
Hey @OlgaMaciaszek,
I opened PR on branch 3.1.x. Is this right?

**Comment by cbezmen** [comment]
Fixes gh-549

**Review by OlgaMaciaszek — APPROVED** [review]
@cbezmen Thanks for the PR. Looks good in general, however, since this method is already used in `Hoxton`, it should probably go to the `2.2.x` branch instead. In order to get it into the upcoming `Hoxton` release, I will cherry-pick this commit to `2.2.x` and add some cosmetic changes.

**Comment by OlgaMaciaszek** [comment]
Fixes gh-549.

**Comment by OlgaMaciaszek** [comment]
Merged with 8c08204c781ecb425912937fafbb25284167b783.

**Pull request closed without merging**
