### PR TITLE
Release RequestAttributes when called asynchronously. Fixes gh-716

### PR DESCRIPTION
**Pull request by vicasong**

### CODE REVIEW

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hello @vicasong, thanks a lot for submitting this PR. Sorry for not getting back to you earlier. Please add a test. Please add your full name with `@author` tag to the class javadoc. Also, could you please submit this PR against `3.1.x` branch instead of `main`, so that we also get it included in the `2021.0.x` release train?

**Comment by OlgaMaciaszek** [comment]
Fixes gh-716.

**Comment by vicasong** [comment]
I will resubmit a new PR

**Comment by vicasong** [comment]
> Hello @vicasong, thanks a lot for submitting this PR. Sorry for not getting back to you earlier. Please add a test. Please add your full name with `@author` tag to the class javadoc. Also, could you please submit this PR against `3.1.x` branch instead of `main`, so that we also get it included in the `2021.0.x` release train?

PR #775  created.

**Pull request closed without merging**
