### PR TITLE
Fix FeignClientBuilder fallback

### PR DESCRIPTION
**Pull request by moziyan**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@moziyan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=197)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=197) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@moziyan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-openfeign&pullRequestId=197)!

**Comment by moziyan** [comment]
For example, I have a "FeignClient" named "TestFeignClient", that's "fallback" should implements "TestFeignClient", rather than itself. sorry!, I am not good at English.

**Comment by ryanjbaxter** [comment]
That is the way it works today so I am not sure what this code is adding

**Comment by moziyan** [comment]
please see https://github.com/spring-cloud/spring-cloud-openfeign/issues/184#issuecomment-503906927

**Comment by spencergibb** [comment]
You're going to have to show us a sample of what couldn't be done before, because I still don't understand

**Comment by moziyan** [comment]
```java
public interface DataDictionaryFeignClient {
    Result<Map<String, DataDictionaryVO>> getByCodes(String[] codes);
}

public class HystrixDataDictionaryFeignClient implements DataDictionaryFeignClient {
    @Override
    public Result<Map<String, DataDictionaryVO>> getByCodes(String[] codes) {
        return null;
    }
}

...

FeignClientBuilder.Builder<DataDictionaryFeignClient> dataDictionaryFeignClientBuilder
                = feignClientBuilder.forType(DataDictionaryFeignClient.class, properties.getServiceName());
dataDictionaryFeignClientBuilder.url(properties.getUrl());

// I will get an error: 'fallback(java.lang.Class<x.x.x.DataDictionaryFeignClient>)' in 'org.springframework.cloud.openfeign.FeignClientBuilder.Builder' cannot be applied to '(java.lang.Class<x.x.x.HystrixDataDictionaryFeignClient>)'
dataDictionaryFeignClientBuilder.fallback(HystrixDataDictionaryFeignClient.class);
dataDictionaryFeignClientBuilder.build();
```

**Comment by ryanjbaxter** [comment]
So it happens when you are building the Feign client yourself?

**Comment by moziyan** [comment]
Yeah!

**Comment by OlgaMaciaszek** [comment]
Fixes gh-184.

**Pull request merged**
