### PR TITLE
Add queryMapEncoder to FeignClientProperties

### PR DESCRIPTION
**Pull request by KENNYSOFT**
From https://github.com/spring-cloud/spring-cloud-openfeign/issues/629#issuecomment-976496995

### CODE REVIEW

**Review by OlgaMaciaszek — APPROVED** [review]
@KENNYSOFT Thanks for submitting the PR. It looks fine, however, more docs should have been added. Since we're planning to release `2021.0.1` today, I'm going to add them, in order to get this into the release.

**Comment by OlgaMaciaszek** [comment]
After a further consideration, although the code looks good, I don't see that it's a needed functionality - the general model of overriding these Feign configuration elements is via adding Java beans as also described in the documentation. Is there a scenario where that is causing an issue? 
I'm going to leave this PR open to get opinions from the community, however, if no compelling reasons will be presented to add this, we'll stay just with the bean config option.

**Comment by KENNYSOFT** [comment]
Actually, `Retryer`, `ErrorDecoder`, and `Capability` are also supported via Java Bean with the way in application.yml. There are not any 'compelling reasons' but it can give more flexibility to set the `QueryMapEncoder`.

**Comment by KENNYSOFT** [comment]
Just found out fe8bbbb6dab491fb9d14e2946cf41af6b096e73a and integrated since v3.1.1; don't care whether i it included in v3.0.x or not for now. Closing with thanks!

**Pull request closed without merging**
